USE QLGV
GO

--Q1--
SELECT GV.HOTEN, GV.LUONG
FROM GIAOVIEN AS GV
WHERE GV.PHAI = N'Nữ'

--Q2--
SELECT GV.HOTEN, GV.LUONG AS LUONG_TRUOC, GV.LUONG * 1.1 AS LUONG_SAU
FROM GIAOVIEN AS GV

--Q3--
SELECT GV.MAGV
FROM GIAOVIEN AS GV
WHERE GV.HOTEN LIKE N'Nguyễn%' AND GV.LUONG > 2000
UNION
SELECT GV.MAGV
FROM GIAOVIEN AS GV, BOMON AS BM
WHERE BM.TRUONGBM = GV.MAGV AND YEAR(BM.NGAYNHANCHUC) > 1995

--Q4--
SELECT GV.HOTEN
FROM GIAOVIEN AS GV, BOMON AS BM, KHOA AS K
WHERE GV.MABM = BM.MABM AND BM.MAKHOA = K.MAKHOA AND K.TENKHOA =  N'Công nghệ thông tin'

--Q5--
SELECT GV.HOTEN AS HoTenTruongBoMon, BM.TENBM AS TenBoMon
FROM GIAOVIEN AS GV, BOMON AS BM
WHERE GV.MAGV = BM.TRUONGBM

--Q6--
SELECT GV.HOTEN AS HoTenGV, BM.TENBM AS TenBoMon
FROM GIAOVIEN AS GV, BOMON AS BM
WHERE GV.MABM = BM.MABM

--Q7--
SELECT GV.HOTEN AS ChuNhiemDeTai, DT.TENDT AS TenDeTai
FROM GIAOVIEN AS GV, DETAI AS DT
WHERE DT.GVCNDT = GV.MAGV

--Q8--
SELECT K.TENKHOA AS TenKhoa, GV.HOTEN AS TenTruongKhoa
FROM GIAOVIEN AS GV, KHOA AS K
WHERE K.TRUONGKHOA = GV.MAGV

--Q9--
SELECT DISTINCT GV.HOTEN AS TenGiaoVien
FROM GIAOVIEN AS GV, BOMON AS BM, THAMGIADT AS TGDT
WHERE GV.MABM = BM.MABM AND BM.TENBM = 'Vi sinh' AND TGDT.MAGV = GV.MAGV AND TGDT.MADT = '006'

--Q10--
SELECT DT.MADT AS MaDeTai, CD.TENCD AS TenChuDe, GV.HOTEN AS TenChuNhiem, GV.NGSINH AS NgaySinh, GV.DIACHI AS DiaChi
FROM DETAI AS DT, CHUDE AS CD, GIAOVIEN AS GV
WHERE DT.CAPQL = N'Trường' AND DT.MACD = CD.MACD AND GV.MAGV = DT.GVCNDT

--Q11--
SELECT GV.HOTEN AS HoTenGV, QL.HOTEN AS HoTenNQL
FROM GIAOVIEN AS GV, GIAOVIEN AS QL
WHERE GV.GVQLCM = QL.MAGV

--Q12-
SELECT GV.HOTEN AS HoTen
FROM GIAOVIEN AS GV, GIAOVIEN AS QL
WHERE GV.GVQLCM = QL.MAGV AND QL.HOTEN = N'Nguyễn An Trung' --Nguyễn Thanh Tùng -> null--

--Q13--
SELECT GV.HOTEN AS HoTen
FROM GIAOVIEN AS GV, BOMON AS BM
WHERE GV.MAGV = BM.TRUONGBM AND BM.TENBM = N'Hệ thống thông tin'

--Q14--
SELECT DISTINCT GV.HOTEN AS TenChuNhiem
FROM GIAOVIEN AS GV, DETAI AS DT, CHUDE AS CD
WHERE GV.MAGV = DT.GVCNDT AND DT.MACD = CD.MACD AND CD.TENCD = N'Quản lý giáo dục'

--Q15--
SELECT CV.TENCV
FROM CONGVIEC AS CV, DETAI AS DT
WHERE CV.MADT = DT.MADT AND DT.TENDT = N'HTTT quản lý các trường ĐH' AND MONTH(CV.NGAYBD) = 3 AND YEAR(CV.NGAYBD) = 2008

--Q16--
SELECT GV.HOTEN AS TenGV, QL.HOTEN AS TenQLCM
FROM GIAOVIEN AS GV, GIAOVIEN AS QL
WHERE GV.GVQLCM = QL.MAGV

--Q17--
SELECT CV.TENCV
FROM CONGVIEC AS CV
WHERE CV.NGAYBD >= '2007-01-01' AND CV.NGAYBD <= '2007-08-01'

--Q18--
SELECT GV.HOTEN
FROM GIAOVIEN AS GV
WHERE GV.MABM = (SELECT BM.MABM FROM BOMON AS BM, GIAOVIEN AS GV WHERE GV.HOTEN = N'Trần Trà Hương' AND GV.MABM = BM.MABM)

--Q19--
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN AS GV, BOMON AS BM, DETAI AS DT
WHERE GV.MAGV = BM.TRUONGBM AND GV.MAGV = DT.GVCNDT

--Q20--
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN AS GV, BOMON AS BM, KHOA AS K
WHERE GV.MAGV = BM.TRUONGBM AND GV.MAGV = K.TRUONGKHOA

--Q21--
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN AS GV, BOMON AS BM, DETAI AS DT
WHERE GV.MAGV = BM.TRUONGBM AND GV.MAGV = DT.GVCNDT

--Q22--
SELECT DISTINCT GV.MAGV
FROM GIAOVIEN AS GV, DETAI AS DT, KHOA AS K
WHERE GV.MAGV = K.TRUONGKHOA AND GV.MAGV = DT.GVCNDT

--Q23--
SELECT GV.MAGV
FROM GIAOVIEN AS GV, BOMON AS BM
WHERE GV.MABM = BM.MABM AND BM.MABM = N'HTTT'
UNION
SELECT GV.MAGV
FROM GIAOVIEN AS GV, THAMGIADT AS TGDT
WHERE TGDT.MADT = '001' AND TGDT.MAGV = GV.MAGV

--Q24--
SELECT GV.MAGV
FROM GIAOVIEN AS GV
WHERE GV.MABM = (SELECT GV.MABM FROM GIAOVIEN AS GV WHERE GV.MAGV = '002') AND GV.MAGV != '002'

--Q25--
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN AS GV, BOMON AS BM
WHERE GV.MAGV = BM.TRUONGBM

--Q26--
SELECT GV.HOTEN, GV.LUONG
FROM GIAOVIEN AS GV