USE QLGV
GO

--Q27--
SELECT COUNT(*) AS SoLuongGiaoVien, SUM(GIAOVIEN.LUONG) AS TongLuong
FROM GIAOVIEN

--Q28--
SELECT BM.TENBM, COUNT(*) AS SoLuongGVBM, AVG(GV.LUONG) AS TBLuong
FROM GIAOVIEN AS GV, BOMON AS BM
WHERE GV.MABM = BM.MABM
GROUP BY BM.MABM, BM.TENBM

--Q29--
SELECT CHUDE.TENCD AS TenChuDe, COUNT(DETAI.MADT) AS SoLuongDeTai
FROM CHUDE, DETAI
WHERE CHUDE.MACD = DETAI.MACD
GROUP BY CHUDE.TENCD

--Q30--
SELECT GV.HOTEN AS TenGV, COUNT(DISTINCT TGDT.MADT) AS SoLuongDTThamGia
FROM GIAOVIEN AS GV, THAMGIADT AS TGDT
WHERE TGDT.MAGV = GV.MAGV
GROUP BY GV.HOTEN

--Q31--
SELECT GV.HOTEN AS TenGV, COUNT(DISTINCT DT.MADT) AS SoLuongDTChuNhiem
FROM GIAOVIEN AS GV, DETAI AS DT
WHERE DT.GVCNDT = GV.MAGV
GROUP BY GV.HOTEN

--Q32--
SELECT GV.HOTEN AS TenGV, COUNT(NT.MAGV) AS SoNguoiThan
FROM GIAOVIEN AS GV
LEFT JOIN NGUOITHAN AS NT ON GV.MAGV = NT.MAGV
GROUP BY GV.HOTEN, GV.MAGV

--Q33--
SELECT GV.HOTEN AS TenGV, COUNT(DISTINCT TGDT.MADT) AS SoLuongDT
FROM GIAOVIEN AS GV, THAMGIADT AS TGDT
WHERE GV.MAGV = TGDT.MAGV
GROUP BY GV.HOTEN, GV.MAGV
HAVING COUNT(DISTINCT TGDT.MADT) >= 2 -- only have >= 2--

--Q34--
SELECT COUNT(DISTINCT TGDT.MAGV) AS SoGV
FROM THAMGIADT AS TGDT, DETAI AS DT
WHERE TGDT.MADT = DT.MADT AND DT.TENDT = N'Nghiên cứu tế bào gốc' -- No one join UDHHXanh--