--Q3--
SELECT GV.MAGV
FROM GIAOVIEN AS GV
WHERE GV.HOTEN LIKE N'Nguyễn%' AND GV.LUONG > 2000
UNION
SELECT GV.MAGV
FROM GIAOVIEN AS GV, BOMON AS BM
WHERE BM.TRUONGBM = GV.MAGV AND YEAR(BM.NGAYNHANCHUC) > 1995

--Q4--
SELECT GV.HOTEN
FROM GIAOVIEN AS GV, BOMON AS BM, KHOA AS K
WHERE GV.MABM = BM.MABM AND BM.MAKHOA = K.MAKHOA AND K.TENKHOA =  N'Công nghệ thông tin'

--Q5--
SELECT GV.HOTEN AS HoTenTruongBoMon, BM.TENBM AS TenBoMon
FROM GIAOVIEN AS GV, BOMON AS BM
WHERE GV.MAGV = BM.TRUONGBM

--Q11--
SELECT GV.HOTEN AS HoTenGV, QL.HOTEN AS HoTenNQL
FROM GIAOVIEN AS GV, GIAOVIEN AS QL
WHERE GV.GVQLCM = QL.MAGV

--Q16--
